### ISSUE TITLE
Function in loadout.hpp comment wrong

### ISSUE THREAD

**Issue by Herbiie** [toadball/tb3_gear.VR#1]
https://github.com/toadball/tb3_gear.VR/blob/master/tb3/loadouts.hpp

Line 1
Reads:
`//Loadouts called with: [this,"side_class","unit_class"] call tb3_fLoadout;`

Should read:
`//Loadouts called with: [this,"side_class","unit_class"] call tb3_fnc_loadout;`

**Comment by toadball** [comment]
Fixed with latest commits.
